name: protenix
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.10
  - pyyaml
  - scipy
  - tqdm
  - pandas
  - scikit-learn
  - numpy=1.26.3
  - matplotlib=3.9.2
  - ipywidgets
  - ninja
  - filelock
  - packaging
  - protobuf=3.20.2
  - wandb
  - biopython=1.83
  - biotite=1.0.1
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pip
  - pip:
    - ml_collections
    - optree
    - rdkit
    - modelcif==0.7
    - scikit-learn-extra
    - deepspeed>=0.15.1
    - icecream
    - ipdb
    - nvidia-cublas-cu12
    - fair-esm
    - py3Dmol

